### ISSUE TITLE
Export more stats + compatibility with other dashboard

### ISSUE THREAD

**Issue by Volkor3-16** [ruscalworld/fabric-exporter#6]
I found [this](https://grafana.com/grafana/dashboards/16508-minecraft-server-stats/) dashboard while looking for a dashboard and mod for a Forge modded server, and by the looks of it, it looks to be a much better dashboard than the one we've got here.

Would it be too much to ask to rename all the exported values to match that dashboard? (and export the same stats)

Hell, even if you don't, having JVM stats would be very nice to see for debugging

**Comment by ruscalworld** [comment]
FabricExporter now comes with JVM metrics provided by `simpleclient_hotspot` package.

Forge mod that you've referenced uses the same package, so its dashboard even will not require any changes in part of JVM metrics for usage with FabricExporter.
