### ISSUE TITLE
Version for 1.20.2

### ISSUE THREAD

**Issue by meza** [ruscalworld/fabric-exporter#8]
Hey,

Is there any chance of a 1.20.2 version?
1.20.1 actually works but it messes up the version detection of the game somehow.
Unfortunately we can't upgrade to .4 just yet

![image](https://github.com/ruscalworld/fabric-exporter/assets/211977/05680c86-f823-4508-b405-a59317520cca)

**Comment by ruscalworld** [comment]
Published a 1.20.2 version on Modrinth: https://modrinth.com/mod/fabricexporter/version/J6hcIgVH
